# rule identifiers to exclude from running
disabled_rules:
- trailing_whitespace

# some rules are only opt-in
opt_in_rules:
- empty_count
- empty_string
# Find all the available rules by running:
# swiftlint rules

# paths to include during linting. `--path` is ignored if present.
# included:
# - src

# paths to ignore during linting. Takes precedence over `included`.
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

# reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
reporter: "xcode"